server:
  port: ${MAIN_SERVICE_PORT}

spring:
  application:
    name: EBOOK-READER-MAIN-SERVICE

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 20MB

gplaybook:
  apikey:
    ${GPLAYBOOKS_APIKEY}

cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

ml:
  service:
    host: ${ML_SERVICE_HOST}
    port: ${ML_SERVICE_PORT}